[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
element_token_factory = "D32BEf4TnLFBtoM1Z2smXY33MxGLT3HJZBGYNfenF7kA"
item_marketplace = "4HvxXhE94xfP3viSZYWyyeuGJGNUH1oHpNF3cLCvWfvt"
price_oracle = "5sJZ28FwcX8QYTPN1z6cryHUC8eHhX5HSdxhaBBxptKz"
treasury_bridge = "8h1aAT9QtnVB1jZWQ3ZuiLdp2KZkyV3xUJQUxSVsQ9Bb"

[programs.localnet]
element_token_factory = "D32BEf4TnLFBtoM1Z2smXY33MxGLT3HJZBGYNfenF7kA"
item_marketplace = "4HvxXhE94xfP3viSZYWyyeuGJGNUH1oHpNF3cLCvWfvt"
price_oracle = "5sJZ28FwcX8QYTPN1z6cryHUC8eHhX5HSdxhaBBxptKz"
treasury_bridge = "8h1aAT9QtnVB1jZWQ3ZuiLdp2KZkyV3xUJQUxSVsQ9Bb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
